// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutTestimonialParallax from "@/components/sections/about/AboutTestimonialParallax";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
              <AboutTestimonialParallax
        textAnimation="fade"
        tag="About Maison ALPILIA"
        quote="In the heart of the Alpilles, surrounded by ancient olive groves and historic vineyards, Maison ALPILIA delivers bespoke 24/7 conciergerie services. From complete villa management to tailored local experiences, we cater to every detail with refined discretion."
        author="Maison ALPILIA"
        role="24/7 Alpilles Concierge — Private Estate & Lifestyle Curation"
        imageSrc="https://picsum.photos/seed/1680035011/1200/800"
        socialLinks={[
                  { icon: "Twitter", label: "Twitter", href: "#" },
                  { icon: "Linkedin", label: "LinkedIn", href: "#" },
                  { icon: "Instagram", label: "Instagram", href: "#" },
                ]}
      />
            </div>
  );
}
