// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutTestimonialParallax from "@/components/sections/about/AboutTestimonialParallax";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
              <AboutTestimonialParallax
        textAnimation="fade"
        tag="About Maison ALPILIA"
        quote="In the heart of the Alpilles, we turn private villas into world-class culinary and cocktail destinations. Available 24 hours a day, 7 days a week, Maison ALPILIA delivers bespoke private chef events and custom home bar experiences without compromise."
        author="Maison ALPILIA"
        role="24/7 Alpilles Concierge — Private Chef & Home Bar Specialist"
        imageSrc="https://storage.googleapis.com/webild/default/templates/creative-portfolio/avatar.webp?_wi=2"
        socialLinks={[
                  { icon: "Twitter", label: "Twitter", href: "#" },
                  { icon: "Linkedin", label: "LinkedIn", href: "#" },
                  { icon: "Instagram", label: "Instagram", href: "#" },
                ]}
      />
            </div>
  );
}
