// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutTestimonialParallax from "@/components/sections/about/AboutTestimonialParallax";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
              <AboutTestimonialParallax
        textAnimation="fade"
        tag="About"
        quote="I don't design to decorate — I design to solve. Sharp, intentional work that moves brands forward."
        author="Maison ALPILIA"
        role="Independent Designer"
        imageSrc="https://storage.googleapis.com/webild/default/templates/creative-portfolio/avatar.webp"
        socialLinks={[
                  { icon: "Twitter", label: "Twitter", href: "#" },
                  { icon: "Linkedin", label: "LinkedIn", href: "#" },
                  { icon: "Instagram", label: "Instagram", href: "#" },
                ]}
      />
            </div>
  );
}
