// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactSplitFormParallax from "@/components/sections/contact/ContactSplitFormParallax";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
              <ContactSplitFormParallax
                textAnimation="fade"
                tag="Get in Touch"
                title="Let's Build"
                description="Have a project in mind? Drop me a message and I'll get back to you within 24 hours."
                inputs={[
                  { name: "name", type: "text", placeholder: "Your name", required: true },
                  { name: "email", type: "email", placeholder: "Your email", required: true }
                ]}
                textarea={{ name: "message", placeholder: "Tell me about your project...", rows: 5, required: true }}
                buttonText="Send Message"
                imageSrc="https://storage.googleapis.com/webild/default/templates/creative-portfolio/contact.webp"
                ctaLinks={[
                  { icon: "Video", label: "Book a Call", href: "#" },
                ]}
              />
            </div>
  );
}
