// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTabbedAccordion from "@/components/sections/faq/FaqTabbedAccordion";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
      <FaqTabbedAccordion
        textAnimation="fade"
        tag="FAQ"
        title="Frequently Asked Questions"
        description="Everything you need to know about Maison ALPILIA's 24/7 private concierge services."
        categories={[{"items":[{"question":"What is Maison ALPILIA?","answer":"Maison ALPILIA is a luxury private conciergerie offering 24/7 lifestyle management, luxury travel, private aviation, estate management, and VIP access."},{"question":"Are you really available 24/7 and 7/7?","answer":"Yes. Our private concierge desk operates 24 hours a day, 7 days a week, 365 days a year to respond instantly to any requirement, anywhere in the world."},{"answer":"We serve Ultra High Net Worth Individuals, international family offices, corporate leaders, and discerning travelers requiring bespoke, high-discretion lifestyle management.","question":"Who are your services designed for?"},{"question":"How do you handle privacy and discretion?","answer":"Absolute discretion is our core principle. Every team member and partner operates under strict Non-Disclosure Agreements, ensuring total confidentiality."}],"name":"General"},{"name":"Membership","items":[{"answer":"We offer private annual memberships as well as bespoke project-based retainers for specific travel, event, or estate needs.","question":"How does membership work?"},{"question":"What benefits do members receive?","answer":"Members receive direct 24/7 communication lines, dedicated lifestyle directors, global priority access, and zero response delay."},{"question":"Can I request individual luxury services without a membership?","answer":"Yes, we accommodate high-value one-off requests such as yacht charters, private jet bookings, or exclusive event access upon review and verification."}]},{"name":"Access","items":[{"question":"How do I request private access or consultation?","answer":"Simply click 'Request Private Access' or contact our direct desk via email or telephone. Our team responds immediately."},{"question":"What is the turnaround time for urgent requests?","answer":"Our emergency lifestyle support desk handles last-minute bookings, emergency travel arrangements, and urgent requests instantly 24/7."}]}]}
        cta={{
                  imageSrc: "https://storage.googleapis.com/webild/default/templates/creative-portfolio/avatar.webp?_wi=3",
                  name: "More questions? Reach out anytime.",
                  role: "joseph@alexandercreative.com",
                  buttonText: "Book a call",
                  buttonHref: "#contact",
                }}
      />
    </div>
  );
}
