// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTabbedAccordion from "@/components/sections/faq/FaqTabbedAccordion";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
      <FaqTabbedAccordion
        textAnimation="fade"
        tag="FAQ"
        title="Frequently Asked Questions"
        description="Everything you need to know about Maison ALPILIA's 24/7 luxury conciergerie services in the Alpilles."
        categories={[{"items":[{"answer":"Maison ALPILIA is an exclusive private conciergerie based in the Alpilles, providing 24/7 villa management, lifestyle assistance, private dining, and bespoke local experiences.","question":"What is Maison ALPILIA?"},{"answer":"Yes. Our concierge team operates 24 hours a day, 7 days a week across Saint-Rémy, Les Baux, and Eygalières to respond to all villa and guest requests.","question":"Are your concierge services available 24/7?"},{"question":"Where do you operate?","answer":"We serve villa owners, estate managers, and luxury guests across Saint-Rémy-de-Provence, Les Baux-de-Provence, Eygalières, and the entire Alpilles region."},{"question":"How do you maintain guest privacy?","answer":"Absolute discretion is guaranteed for every assignment. All staff and partners adhere to strict confidentiality protocols."}],"name":"General"},{"items":[{"question":"How can I request concierge services?","answer":"We offer both bespoke single-request assistance (vineyard bookings, private dining, transfers) and full-season villa conciergerie retainers."},{"answer":"Yes, we handle last-minute requests 24/7 across the Alpilles, from urgent villa arrangements to private chef placements.","question":"Do you handle urgent or last-minute requests?"}],"name":"Services"}]}
        cta={{
                  imageSrc: "https://storage.googleapis.com/webild/default/templates/creative-portfolio/avatar.webp?_wi=3",
                  name: "More questions? Reach out anytime.",
                  role: "joseph@alexandercreative.com",
                  buttonText: "Book a call",
                  buttonHref: "#contact",
                }}
      />
    </div>
  );
}
