// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTabbedAccordion from "@/components/sections/faq/FaqTabbedAccordion";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
      <FaqTabbedAccordion
        textAnimation="fade"
        tag="FAQ"
        title="Frequently Asked Questions"
        description="Everything you need to know about Maison ALPILIA's private chef and home bar services in the Alpilles."
        categories={[{"items":[{"question":"What is Maison ALPILIA?","answer":"Maison ALPILIA is an exclusive private conciergerie based in the Alpilles, specializing in 24/7 private chef dining, bespoke home bar setups, and villa event curation."},{"answer":"Yes. Our concierge team in the Alpilles operates 24 hours a day, 7 days a week to handle chef requests, home bar installations, and event planning at any hour.","question":"Are your private chef and bar services available 24/7?"},{"question":"Where do you operate?","answer":"We serve villa owners, seasonal luxury guests, and estate managers across Saint-Rémy-de-Provence, Les Baux-de-Provence, Eygalières, and the wider Alpilles region."},{"question":"How do you handle privacy during private estate events?","answer":"Absolute discretion is guaranteed. All private chefs, mixologists, and service staff adhere to strict confidentiality agreements."}],"name":"General"},{"name":"Services","items":[{"question":"How do I book a private chef or home bar experience?","answer":"We provide both single-event bookings (private chef dinners, cocktail parties) and seasonal retainers for comprehensive villa concierge management."},{"question":"Can I request same-day or urgent event services?","answer":"Yes, we accommodate last-minute culinary requests, sommelier wine deliveries, and cocktail bar setups across the Alpilles 24/7."}]}]}
        cta={{
                  imageSrc: "https://storage.googleapis.com/webild/default/templates/creative-portfolio/avatar.webp?_wi=3",
                  name: "More questions? Reach out anytime.",
                  role: "joseph@alexandercreative.com",
                  buttonText: "Book a call",
                  buttonHref: "#contact",
                }}
      />
    </div>
  );
}
