// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroWorkScrollStack from "@/components/sections/hero/HeroWorkScrollStack";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
      <HeroWorkScrollStack
                textAnimation="fade"
                heroAnimationDelay={4}
                tag="1 spot left this month"
                title="Design that"
                titleHighlight="commands attention."
                description="Design engineered for performance, not just aesthetics."
                descriptionMuted="I craft every visual touchpoint your brand needs to capture attention and convert it into revenue."
                primaryButton={{
                  text: "Book a call with me",
                  href: "#contact",
                  avatarSrc: "https://storage.googleapis.com/webild/default/templates/creative-portfolio/avatar.webp",
                  avatarLabel: "You",
                }}
                sectionTag="Selected Work"
                sectionTitle="Projects That Speak for Themselves"
                sectionDescription="A curated selection of design work that drove real business results for ambitious brands."
                items={[
                  {
                    title: "HydroFlow Product Launch",
                    description: "Beverage brand shoot. Every frame engineered to sell.",
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/creative-portfolio/screen-1.webp",
                    tag: "Product Shot",
                  },
                  {
                    title: "Webild Athlete Campaign",
                    description: "Sports tech shoot. Wearables captured in raw motion.",
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/creative-portfolio/screen-2.webp",
                    tag: "Photography",
                  },
                  {
                    title: "Maru Residence",
                    description: "Architectural interior shoot. Minimal compositions.",
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/creative-portfolio/screen-3.webp",
                    tag: "Interior Design",
                  },
                ]}
                secondaryButton={{ text: "View all my projects", href: "#" }}
              />
    </div>
  );
}
