// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroWorkScrollStack from "@/components/sections/hero/HeroWorkScrollStack";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
      <HeroWorkScrollStack
        textAnimation="fade"
        heroAnimationDelay={4}
        tag="24/7 & 7/7 Luxury Concierge"
        title="Bespoke Luxury,"
        titleHighlight="Always Available."
        description="Exclusive private concierge & lifestyle management for discerning clientele worldwide."
        descriptionMuted="Maison ALPILIA delivers round-the-clock luxury services, bespoke travel, estate management, and VIP access 24/7, 7 days a week."
        primaryButton={{"avatarLabel":"24/7 Direct","href":"#contact","avatarSrc":"https://storage.googleapis.com/webild/default/templates/creative-portfolio/avatar.webp","text":"Request Private Access"}}
        sectionTag="Living Portfolio"
        sectionTitle="Besposke Curation & VIP Access"
        sectionDescription="A showcase of bespoke lifestyle curation, VIP access, and luxury experiences delivered round-the-clock by Maison ALPILIA."
        items={[{"description":"End-to-end estate preparation, private chef placement, and helicopter charter in Courchevel.","imageSrc":"https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?q=80&w=1200&auto=format&fit=crop","title":"Private Alpine Estate Curation","tag":"Estate & Chalet"},{"tag":"Yachting & VIP","title":"Yacht Charter & Riviera Access","imageSrc":"https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?q=80&w=1200&auto=format&fit=crop","description":"Seamless Mediterranean voyage with dedicated on-board concierge and private dining."},{"description":"Front-row access to exclusive Paris Fashion Week galas and private watchmaker previews.","title":"Exclusive Event & Gala Access","tag":"VIP Access","imageSrc":"https://images.unsplash.com/photo-1511578314322-379afb476865?q=80&w=1200&auto=format&fit=crop"}]}
        secondaryButton={{"href":"#services","text":"Explore All Services"}}
      />
    </div>
  );
}
