// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "services" section.

import React from 'react';
import FeaturesBentoGridCta from "@/components/sections/features/FeaturesBentoGridCta";

export default function ServicesSection(): React.JSX.Element {
  return (
    <div id="services" data-section="services">
              <FeaturesBentoGridCta
                textAnimation="fade"
                tag="Services"
                title="What I Bring to the Table"
                description="End-to-end creative services designed to make your brand impossible to ignore — from the first frame to the final pixel."
                features={[
                  { title: "Photography", description: "Art-directed shoots that capture your brand's personality. Every image is color-graded and built to stop the scroll.", imageSrc: "https://storage.googleapis.com/webild/default/templates/creative-portfolio/photography.webp" },
                  { title: "Product Design", description: "User-centered interfaces for apps and SaaS products. From wireframe to pixel-perfect UI — intuitive experiences that keep users coming back.", imageSrc: "https://storage.googleapis.com/webild/default/templates/creative-portfolio/product-design.webp" },
                  { title: "Website", description: "Conversion-focused websites that look sharp and perform. Clean layouts, strategic CTAs, and responsive design that turns traffic into revenue.", imageSrc: "https://storage.googleapis.com/webild/default/templates/creative-portfolio/website.webp" },
                  { title: "Videos", description: "Brand films and product videos engineered for engagement. Story-driven visuals that convert viewers into customers.", imageSrc: "https://storage.googleapis.com/webild/default/templates/creative-portfolio/videos.webp" },
                ]}
                ctaButton={{
                  text: "Book a call with me",
                  href: "#contact",
                  avatarSrc: "https://storage.googleapis.com/webild/default/templates/creative-portfolio/avatar.webp",
                  avatarLabel: "You",
                }}
              />
            </div>
  );
}
