// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "services" section.

import React from 'react';
import FeaturesBentoGridCta from "@/components/sections/features/FeaturesBentoGridCta";

export default function ServicesSection(): React.JSX.Element {
  return (
    <div id="services" data-section="services">
              <FeaturesBentoGridCta
        textAnimation="fade"
        tag="Alpilles Conciergerie"
        title="Tailored Luxury Services in the Alpilles"
        description="Comprehensive 24/7 conciergerie assistance tailored for luxury estates, villa owners, and guests throughout the Alpilles region."
        features={[{"title":"Villa & Estate Care","imageSrc":"https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=800&auto=format&fit=crop","description":"Full estate oversight, maintenance, pool & garden care, and keyholding amidst Alpilles luxury villas and olive groves."},{"description":"Private vineyard tours, sommelier bookings, and local Alpilles wine sourcing directly to your villa cellar.","imageSrc":"https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?q=80&w=800&auto=format&fit=crop","title":"Vineyard & Wine Curation"},{"description":"Round-the-clock reservation desk, private transportation, local recommendations, and bespoke outdoor excursions in Alpilles nature.","title":"24/7 Lifestyle & Transport","imageSrc":"https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=800&auto=format&fit=crop"},{"title":"Private Dining & Luxury Villas","description":"In-villa dining with private chefs, master mixologists, and tailored aperitifs in your private villa estate.","imageSrc":"https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=800&auto=format&fit=crop"}]}
        ctaButton={{"avatarSrc":"https://storage.googleapis.com/webild/default/templates/creative-portfolio/avatar.webp","href":"#contact","text":"Connect with Concierge","avatarLabel":"24/7 Desk"}}
      />
            </div>
  );
}
