// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonial" section.

import React from 'react';
import TestimonialTrustCard from "@/components/sections/testimonial/TestimonialTrustCard";

export default function TestimonialSection(): React.JSX.Element {
  return (
    <div id="testimonial" data-section="testimonial">
      <TestimonialTrustCard
                textAnimation="fade"
                quote="Working with Maison ALPILIA felt like having a seasoned design partner who truly understood our vision for KYMA and brought it to life in ways we hadn't even imagined."
                rating={5}
                author="Thomas Weber — Co-founder of KYMA"
                avatars={[
                  { name: "Thomas Weber", imageSrc: "https://randomuser.me/api/portraits/men/75.jpg" },
                ]}
              />
    </div>
  );
}
