// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonial" section.

import React from 'react';
import TestimonialTrustCard from "@/components/sections/testimonial/TestimonialTrustCard";

export default function TestimonialSection(): React.JSX.Element {
  return (
    <div id="testimonial" data-section="testimonial">
      <TestimonialTrustCard
        textAnimation="fade"
        quote="Maison ALPILIA has transformed how we manage our properties and travel. Available at 3 AM or mid-flight, their execution and discretion are unparalleled."
        rating={5}
        author="Thomas Weber — Family Office Principal, Monaco"
        avatars={[
                  { name: "Thomas Weber", imageSrc: "https://randomuser.me/api/portraits/men/75.jpg" },
                ]}
      />
    </div>
  );
}
